#!/usr/bin/env python
'''
PALIN toolbox v0.1
December 2022, Aynaz Adl Zarrabi, JJ Aucouturier (CNRS/UBFC)

Functions for kernel calculating method in Classification images
'''

import pandas as pd
import numpy as np
import os.path
import warnings
import ast
from .inverse_model import InverseModel
from .double_pass import DoublePass


class GridSearchModel(InverseModel):
    ''' 
    This class implements an InverseModel to estimate internal noise and criteria using a Grid simulation. This is the default method in Ponsot et al. 
    '''

    @classmethod
    def __str__(cls): 
        return 'GridSearch Inverse model'

    @classmethod
    def build(cls, model_file, internal_noise_range=np.linspace(0,5,50, endpoint=True),criteria_range=np.linspace(-5,5,11, endpoint=True), n_repeated_trials=100, n_runs=10, **kwargs): 
        '''
        Build a lookup model that associates a range of internal noise and criteria values with their corresponding (simulated) prob_agree and prob_first.
        This uses a simulated LinearObserver, and returns the model as a dataframe 
        '''
        print('%s: Building model'%cls)

        # deferred imports of the simulation modules, to avoid circular imports
        from ..simulation.observers.linear_observer import LinearObserver
        from ..simulation.trial import Int2Trial 
        from ..simulation.experiments.double_pass_experiment import DoublePassExperiment
        from ..simulation.trial import Int2Trial, Int1Trial 
        from ..simulation.analysers.agreement_statistics import AgreementStatistics
        from ..simulation.simulation import Simulation as Sim
        from .double_pass import DoublePass
        
        # make kwarg values iterables if needed
        for kw in kwargs:
            if not isinstance(kwargs[kw], list): 
                kwargs[kw] = [kwargs[kw]]  

        observer_params = {'kernel':[[1]],
                   'internal_noise_std':internal_noise_range, 
                  'criteria':criteria_range}
        experiment_params = {'n_trials':[n_repeated_trials],
                     'n_repeated':[n_repeated_trials],
                     'trial_type': [Int2Trial],
                     'n_features': [1],
                     'external_noise_std': [1]}
        analyser_params = {'internal_noise_extractor': [DoublePass]}

        sim = Sim(DoublePassExperiment, experiment_params,
              LinearObserver, observer_params, 
              AgreementStatistics, analyser_params)

        sim_df = sim.run_all(n_runs=n_runs)
        
        # average measures over all runs
        sim_df = sim_df.groupby(['internal_noise_std','criteria'])[AgreementStatistics.get_metric_names()].mean()
        
        sim_df.to_csv(model_file)

        return sim_df      


    @classmethod
    def run(cls, prob_agree, prob_first, model_file=None, **kwargs):
        '''
        Uses a model (a dataframe previously generated by @build_model and stored as a .csv file), previously built with build_model(). 
        Searches through a range of possible internal noise and criteria values
        '''
        from ..simulation.analysers.agreement_statistics import AgreementStatistics

        if (not model_file): 
            raise ValueError('no model file provided for GridSearchModel: use GridSearchModel.build_model() first') 
        elif (not os.path.isfile(model_file)): 
            raise ValueError('Can"t open model file provided for GridSearchModel: %s'%model_file)

        else: 
            model_df = pd.read_csv(model_file)
            # issue error if the model file has several values/runs per internal noise level
            if (model_df.groupby(['internal_noise_std','criteria']).prob_agree.count()>1).any(): 
                print('Warning: the provided model has several runs per value; applying groupby')
                model_df = model_df.groupby(['internal_noise_std','criteria'], 
                    as_index=False)[AgreementStatistics.get_metric_names()].mean() 
                
        # find internal_noise & criteria settings that minimizes distance to prob_agree and prob_first 
        model_df['dist'] = model_df.apply(lambda row: (row.prob_agree-prob_agree)**2 + (row.prob_first-prob_first)**2, axis=1)

        # todo: consider putting a prior on small internal_noise and small criteria
        best_match = model_df[model_df.dist==model_df.dist.min()]

        return best_match.internal_noise_std.iloc[0], best_match.criteria.iloc[0]
