#!/usr/bin/env python
'''
PALIN toolbox v0.1
December 2022, Aynaz Adl Zarrabi, JJ Aucouturier (CNRS/UBFC)

Functions for kernel calculating method in Classification images
'''

import pandas as pd
import numpy as np
import os.path
import warnings
import ast
from .inverse_model import InverseModel
from scipy.optimize import minimize
from scipy.interpolate import RegularGridInterpolator
import pickle


class MinimizeSurrogateModel(InverseModel):
    ''' 
    This class builds a surrogate interpolation function from GridSearchModel, and then minimizes it 
    '''

    @classmethod
    def __str__(cls): 
        return 'MinimizeSurrogate Inverse model'


    @classmethod
    def build_surrogate(cls,df, x_col='internal_noise_std', y_col='criteria', val_col='prob_agree', surrogate_method='pchip'): 
    
        df = df.sort_values(by=[x_col, y_col], ascending=True)
    
        xs = df[x_col].unique()
        ys = df[y_col].unique()
        vals = df[val_col].values
        vals = vals.reshape(len(xs),len(ys))

        return RegularGridInterpolator((xs,ys),vals, method=surrogate_method, bounds_error=False)

    @classmethod
    def build(cls, model_file, grid_model_file,  **kwargs): 
        '''
        Build a surrogate function that interpolates from a grid model that associates a range of internal noise and criteria values with their corresponding (simulated) prob_agree and prob_first.
        '''

        if (not grid_model_file): 
            raise ValueError('no grid model file provided for MinimizeSurrogateModel: use GridSearchModel.build_model() first') 
        elif (not os.path.isfile(grid_model_file)): 
            raise ValueError('Can"t open grid_model_file file provided for MinimizeSurrogateModel: %s'%grid_model_file)
        else: 

            from ..simulation.analysers.agreement_statistics import AgreementStatistics

            if 'surrogate_method' not in kwargs:
                raise ValueError('MinimizeSurrogateModel missing required argument surrogate_method')
            surrogate_method = kwargs['surrogate_method']

            if 'surrogate_method' not in kwargs:
                raise ValueError('MinimizeSurrogateModel missing required argument surrogate_method')
            surrogate_method = kwargs['surrogate_method']


            grid_model_df = pd.read_csv(grid_model_file)

            [prob_agree_name, prob_first_name] = AgreementStatistics.get_metric_names()

            prob_agree_surrogate = cls.build_surrogate(df=grid_model_df, val_col=prob_agree_name, surrogate_method=surrogate_method)
            prob_first_surrogate = cls.build_surrogate(df=grid_model_df, val_col=prob_first_name, surrogate_method=surrogate_method)

            # also save search bounds for minimization, as the bounds of the grid model
            search_bounds = [(grid_model_df['internal_noise_std'].min(),
                            grid_model_df['internal_noise_std'].max()), 
                        (grid_model_df['criteria'].min(),
                            grid_model_df['criteria'].max())]


            surrogates = {"prob_agree": prob_agree_surrogate,
                        "search_bounds":search_bounds,
                        "prob_first" : prob_first_surrogate}

            with open(model_file, 'wb') as file_handle:
                pickle.dump(surrogates , file_handle)

            return prob_agree_surrogate, prob_first_surrogate     


    @classmethod
    def run(cls, prob_agree, prob_first, model_file=None, **kwargs):
        '''
        Uses a model (a dataframe previously generated by @build_model and stored as a .csv file), previously built with build_model(). 
        Searches through a range of possible internal noise and criteria values
        '''
        warnings.filterwarnings("ignore")

        if (not model_file): 
            raise ValueError('no model file provided for MinimizeSurrogateModel: use MinimizeSurrogateModel.build_model() first') 
        elif (not os.path.isfile(model_file)): 
            raise ValueError('Can"t open model file provided for MinimizeSurrogateModel: %s'%model_file)

        else: 
            with open(model_file, 'rb') as file_handle:
                surrogates = pickle.load(file_handle)
            prob_agree_surrogate = surrogates["prob_agree"]
            prob_first_surrogate = surrogates["prob_first"]
            search_bounds = surrogates["search_bounds"]

            if 'minimize_method' not in kwargs:
                raise ValueError('MinimizeSurrogateModel missing required argument minimize_method')
            minimize_method = kwargs['minimize_method']

            print('prob_agree %.2f prob_first %.2f'%(prob_agree,prob_first))
            print(search_bounds)


            def obj(x, *args):
                return (prob_agree_surrogate(x)[0] - prob_agree)**2 + (prob_first_surrogate(x)[0] - prob_first)**2 
            
            res = minimize(obj, [1,0], method=minimize_method, tol=1e-2, bounds=search_bounds)
            
            return res.x[0], res.x[1]

